/***************************************************************
 * This file is automatically generated. Please do not modify.
 ***************************************************************/

import { AccountModel } from "./account.js";
import { TodoModel } from "./todo.js";
import {
  registerModel,
  type Collection,
  type Filter,
  type StringFilter,
} from "accel-record";

declare module "accel-record" {
  function meta<T>(model: T): Meta<T>;

  interface Relation<T, M> {}
}

type Meta<T> = T extends typeof AccountModel | AccountModel
  ? AccountMeta
  : T extends typeof TodoModel | TodoModel
    ? TodoMeta
    : any;

export namespace $Enums {
  export const Status = {
    OPEN: "OPEN",
    CLOSED: "CLOSED",
  } as const;
  export type Status = (typeof Status)[keyof typeof Status];
}

export type Status = $Enums.Status;
export const Status = $Enums.Status;

declare module "./account" {
  interface AccountModel {
    id: number | undefined;
    email: string | undefined;
    passwordDigest: string | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
    get todos(): TodoCollection<TodoModel>;
    set todos(value: TodoModel[]);
  }
}
export interface NewAccount extends AccountModel {}
export class Account extends AccountModel {}
export interface Account extends AccountModel {
  id: number;
  email: string;
  passwordDigest: string;
  createdAt: Date;
  updatedAt: Date;
  get todos(): TodoCollection<Todo>;
  set todos(value: TodoModel[]);
}
type AccountCollection<T extends AccountModel> =
  | Collection<T, AccountMeta>
  | Collection<Account, AccountMeta>;
type AccountMeta = {
  Base: AccountModel;
  New: NewAccount;
  Persisted: Account;
  AssociationKey: "todos";
  Column: {
    id: number;
    email: string;
    passwordDigest: string;
    createdAt: Date;
    updatedAt: Date;
  };
  CreateInput: {
    id?: number;
    email: string;
    passwordDigest?: string;
    password?: string;
    passwordConfirmation?: string;
    createdAt?: Date;
    updatedAt?: Date;
    todos?: TodoModel[];
  };
  WhereInput: {
    id?: number | number[] | Filter<number> | null;
    email?: string | string[] | StringFilter | null;
    passwordDigest?: string | string[] | StringFilter | null;
    createdAt?: Date | Date[] | Filter<Date> | null;
    updatedAt?: Date | Date[] | Filter<Date> | null;
  };
};
registerModel(Account);

declare module "./todo" {
  interface TodoModel {
    id: number | undefined;
    title: string | undefined;
    content: string | undefined;
    status: Status;
    account: Account | undefined;
    accountId: number | undefined;
    createdAt: Date | undefined;
    updatedAt: Date | undefined;
  }
}
export interface NewTodo extends TodoModel {}
export class Todo extends TodoModel {}
export interface Todo extends TodoModel {
  id: number;
  title: string;
  account: Account;
  accountId: number;
  createdAt: Date;
  updatedAt: Date;
}
type TodoCollection<T extends TodoModel> =
  | Collection<T, TodoMeta>
  | Collection<Todo, TodoMeta>;
type TodoMeta = {
  Base: TodoModel;
  New: NewTodo;
  Persisted: Todo;
  AssociationKey: "account";
  Column: {
    id: number;
    title: string;
    content: string | undefined;
    status: Status;
    accountId: number;
    createdAt: Date;
    updatedAt: Date;
  };
  CreateInput: {
    id?: number;
    title: string;
    content?: string;
    status?: Status;
    createdAt?: Date;
    updatedAt?: Date;
  } & ({ account: Account } | { accountId: number });
  WhereInput: {
    id?: number | number[] | Filter<number> | null;
    title?: string | string[] | StringFilter | null;
    content?: string | string[] | StringFilter | null;
    status?: Status | Status[] | undefined | null;
    account?: Account | Account[];
    accountId?: number | number[] | Filter<number> | null;
    createdAt?: Date | Date[] | Filter<Date> | null;
    updatedAt?: Date | Date[] | Filter<Date> | null;
  };
};
registerModel(Todo);
