/* eslint-disable */
/***************************************************************
 * This file is automatically generated. Please do not modify.
 ***************************************************************/

import { type DataSource } from "@prisma/generator-helper";

import {
  generateDatabaseConfig,
  registerModel,
  type Collection,
  type Filter,
  type StringFilter,
} from "accel-record";
import { Attribute, defineEnumTextAttribute } from "accel-record/enums";

declare module "accel-record" {
  function meta<T>(model: T): Meta<T>;

  interface Relation<T, M> {}
}

type Meta<T> = any;

export const schemaDir = "../../db/";
export const sourceFilePath = "../../db/schema/main.prisma";
export const dataSource = {
  name: "db",
  provider: "sqlite",
  activeProvider: "sqlite",
  url: {
    fromEnvVar: "DATABASE_URL",
    value: null,
  },
  schemas: [],
} as DataSource;

/**
 * Retrieves the database connection settings based on the Prisma schema file.
 */
export const getDatabaseConfig = () =>
  generateDatabaseConfig(dataSource, import.meta.url, schemaDir, sourceFilePath);
