/* eslint-disable */
/***************************************************************
 * This file is automatically generated. Please do not modify.
 ***************************************************************/

import { UserModel } from "./user.js";
import { registerModel, type Collection, type Filter, type StringFilter } from "accel-record";
import { Attribute, defineEnumTextAttribute } from "accel-record/enums";

declare module "accel-record" {
  function meta<T>(model: T): Meta<T>;

  interface Relation<T, M> {}
}

type Meta<T> = T extends typeof UserModel | UserModel ? UserMeta : any;

declare module "./user" {
  interface UserModel {
    id: number | undefined;
    firstName: string | undefined;
    lastName: string | undefined;
    age: number | undefined;
  }
}
export interface NewUser extends UserModel {}
export class User extends UserModel {}
export interface User extends UserModel {
  id: number;
  firstName: string;
  lastName: string;
}
type UserAssociationKey = never;
type UserCollection<T extends UserModel> = Collection<T, UserMeta> | Collection<User, UserMeta>;
type UserMeta = {
  Base: UserModel;
  New: NewUser;
  Persisted: User;
  PrimaryKey: number;
  AssociationKey: UserAssociationKey;
  JoinInput: UserAssociationKey | UserAssociationKey[];
  Column: {
    id: number;
    firstName: string;
    lastName: string;
    age: number | undefined;
  };
  CreateInput: {
    id?: number;
    firstName: string;
    lastName: string;
    age?: number;
  };
  WhereInput: {
    id?: number | number[] | Filter<number> | null;
    firstName?: string | string[] | StringFilter | null;
    lastName?: string | string[] | StringFilter | null;
    age?: number | number[] | Filter<number> | null;
  };
};
registerModel(User);
