/* eslint-disable */
/***************************************************************
* This file is automatically generated. Please do not modify.
***************************************************************/

export const schemaDir = "/Users/koyopro/Documents/repos/accella/tests/prisma";
export const sourceFilePath = "/Users/koyopro/Documents/repos/accella/tests/prisma/schema.prisma";
export const dataSource = {
  "name": "db",
  "provider": "sqlite",
  "activeProvider": "sqlite",
  "url": {
    "fromEnvVar": "DATABASE_URL",
    "value": null
  },
  "schemas": []
};
